#name: Publish Package
#
#on:
#  pull_request:
#    branches:
#      - feature_ci/cd
#
#  schedule:
#    - cron: '0 0 * * 2'
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Install Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#
#      - name: Run Play test in SampleProject
#        run: |
#          cd example/SampleProject/
#          flutter test test/test_play.dart
#
#      - name: Run Publish test in SampleProject
#        run: |
#          cd example/SampleProject/
#          flutter test test/test_publish.dart
#
#      - name: Build APK
#        run: |
#          cd example/SampleProject/
#          flutter build apk
#
#      - name: Build Web
#        run: |
#          cd example/SampleProject/
#          flutter build web --release
#
#
      # Uncomment and adjust for publishing your package
      # - name: Setup Pub Credentials
      #   shell: bash
      #   env:
      #     PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
      #     PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
      #     PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
      #     PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
      #   run: |
      #     sh ./pub_login.sh

      # - name: Check Publish Warnings
      #   run: |
      #      sudo cat /$HOME/.config/dart/pub-credentials.json
      #      flutter pub publish --dry-run

      # - name: Publish Package
      #   run: |
      #       yes | flutter pub publish


name: Publish Package

on:
  pull_request:
    branches:
      - feature_ci/cd

  schedule:
    - cron: '0 0 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 27
          build-tools: 34.0.0
          target: default
          components: "platform-tools"

      - name: Get AVD Devices
        run: |
          device=$(avdmanager list device | grep "id:" | head -n 1 | awk '{print $2}')
          echo "Selected device: $device"
          echo "DEVICE_PROFILE=$device" >> $GITHUB_ENV

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          target: google_apis
          arch: x86_64
          profile: ${{ env.DEVICE_PROFILE }}
          script: |
            adb wait-for-device
            flutter test integration_test/test_play.dart