name: Publish Package

on:
  pull_request:
    branches:
      - feature_ci/cd

  schedule:
  - cron: '0 0 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: |
          flutter pub get
          cd example/SampleProject/
          flutter pub get

      - name: Install Android SDK
        uses: malinskiy/action-android@v3
        with:
          api-level: 31  # API level can be changed based on your requirement
          target: default
          arch: x86_64
          profile: default
          ndk: false

      - name: Create and Start Emulator
        run: |
            sudo apt-get install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
            sudo adduser `id -un` libvirt
            sudo adduser `id -un` kvm
            avdmanager create avd -n test -k "system-images;android-31;default;x86_64" --device "pixel"
            emulator -avd test -no-skin -no-window -no-audio -no-boot-anim &

      - name: Wait for Emulator to Start
        run: |
          adb wait-for-device
          adb shell input keyevent 82  # Unlock screen
          timeout-minutes: 5

      - name: Run Tests in Root Directory
        run: flutter test

      - name: Run Play test in SampleProject
        run: |
          cd example/SampleProject/
          flutter test -d emulator-5554 integration_test/test_play.dart

      - name: Run Publish test in SampleProject
        run: |
          cd example/SampleProject/
          flutter test -d emulator-5554 integration_test/test_publish.dart

      - name: Build APK
        run: |
          cd example/SampleProject/
          flutter build apk

      - name: Build Web
        run: |
          cd example/SampleProject/
          flutter build web --release

      # - name: Setup Pub Credentials
      #   shell: bash
      #   env:
      #     PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
      #     PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
      #     PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
      #     PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
      #   run: |
      #     sh ./pub_login.sh
      
      # - name: Check Publish Warnings
      #   run: |
      #      sudo cat /$HOME/.config/dart/pub-credentials.json
      #      flutter pub publish --dry-run
      
      # - name: Publish Package
      #   run: |
      #       yes | flutter pub publish