name: Publish Package

on:
  pull_request:
    branches:
      - feature_ci/cd

  schedule:
  - cron: '0 0 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'


      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" "system-images;android-30;google_apis;x86_64" "emulator"
          sdkmanager --install "cmdline-tools;latest"

      - name: Start Android Emulator
        run: |
          avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"
          $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-window -no-audio &

      - name: Wait for Android Emulator to Boot
        run: |
          adb wait-for-device
          adb shell input keyevent 82
          
      - name: Install dependencies
        run: |
          flutter pub get
          cd example/SampleProject/
          flutter pub get

      - name: Run Tests in Root Directory
        run: flutter test

      - name: Run Play test in SampleProject
        run: |
          cd example/SampleProject/
          flutter test integration_test/test_play.dart

      - name: Run Publish test in SampleProject
        run: |
          cd example/SampleProject/
          flutter test integration_test/test_publish.dart

      - name: Build APK
        run: |
          cd example/SampleProject/
          flutter build apk

      - name: Build Web
        run: |
          cd example/SampleProject/
          flutter build web --release

      # - name: Setup Pub Credentials
      #   shell: bash
      #   env:
      #     PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
      #     PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
      #     PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
      #     PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
      #   run: |
      #     sh ./pub_login.sh
      
      # - name: Check Publish Warnings
      #   run: |
      #      sudo cat /$HOME/.config/dart/pub-credentials.json
      #      flutter pub publish --dry-run
      
      # - name: Publish Package
      #   run: |
      #       yes | flutter pub publish