name: Publish Package

on:
  pull_request:
    branches:
      - feature_ci/cd

  schedule:
  - cron: '0 0 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: |
          flutter pub get
          cd example/SampleProject/
          flutter pub get

      - name: Run Tests in Root Directory
        run: flutter test

      - name: Run Tests in SampleProject
        run: |
          cd example/SampleProject/
          flutter test integration_test/test_play.dart

      - name: Build APK
        run: |
          cd example/SampleProject/
          flutter build apk

      - name: Build Web
        run: |
          cd example/SampleProject/
          flutter build web --release

#      - name: Build iOS
#        if: runner.os == 'macOS'
#        run: |
#          cd example/SampleProject/
#          pod repo update
#          flutter build ios --release --no-codesign
        

      # - name: Setup Pub Credentials
      #   shell: bash
      #   env:
      #     PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
      #     PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
      #     PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
      #     PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
      #   run: |
      #     sh ./pub_login.sh
      
      # - name: Check Publish Warnings
      #   run: |
      #      sudo cat /$HOME/.config/dart/pub-credentials.json
      #      flutter pub publish --dry-run
      
      # - name: Publish Package
      #   run: |
      #       yes | flutter pub publish