name: Publish Package

on:
  pull_request:
    branches:
      - feature_ci/cd

  schedule:
    - cron: '0 0 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up Android SDK
        run: |
          apt-get update
          apt-get install -y lib32stdc++6 lib32z1
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          mkdir -p $ANDROID_HOME/cmdline-tools
          unzip -q commandlinetools-linux-8512546_latest.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/tools
          yes | $ANDROID_HOME/cmdline-tools/tools/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/tools/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" "system-images;android-30;google_apis;x86_64" "emulator"
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          PATH: $ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools:$PATH

      - name: Start Android Emulator
        run: |
          echo "Starting emulator"
          $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-window -no-audio &
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          PATH: $ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$PATH

      - name: Wait for Android Emulator to Boot
        run: |
          adb wait-for-device
          adb shell input keyevent 82

      - name: Install dependencies
        run: |
          flutter pub get
          cd example/SampleProject/
          flutter pub get

      - name: Run Tests in Root Directory
        run: flutter test

      - name: Run Play test in SampleProject
        run: |
          cd example/SampleProject/
          flutter test integration_test/test_play.dart

      - name: Run Publish test in SampleProject
        run: |
          cd example/SampleProject/
          flutter test integration_test/test_publish.dart

      - name: Build APK
        run: |
          cd example/SampleProject/
          flutter build apk

      - name: Build Web
        run: |
          cd example/SampleProject/
          flutter build web --release

      # Uncomment and adjust for publishing your package
      # - name: Setup Pub Credentials
      #   shell: bash
      #   env:
      #     PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
      #     PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
      #     PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
      #     PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
      #   run: |
      #     sh ./pub_login.sh
      
      # - name: Check Publish Warnings
      #   run: |
      #      sudo cat /$HOME/.config/dart/pub-credentials.json
      #      flutter pub publish --dry-run
      
      # - name: Publish Package
      #   run: |
      #       yes | flutter pub publish