name: Publish Package

on:
  pull_request:
    branches:
      - feature_ci/cd

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: |
          flutter pub get
          cd example/SampleProject/
          flutter pub get
      
      - name: Run Tests
        run: |
          flutter test
      
      - name: Build APK
        run: |
          cd example/SampleProject/
          flutter build apk

      - name: Build Web
        if: runner.os == 'macOS'
        run: |
          cd example/SampleProject/
          flutter build ios --release --no-codesign

      - name: Build iOS
        if: runner.os == 'macOS'
        run: cd example/SampleProject/ | ls | flutter build ios --release --no-codesign
        
      # - name: Setup Pub Credentials
      #   shell: bash
      #   env:
      #     PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
      #     PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
      #     PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
      #     PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
      #   run: |
      #     sh ./pub_login.sh
      
      # - name: Check Publish Warnings
      #   run: |
      #      sudo cat /$HOME/.config/dart/pub-credentials.json
      #      flutter pub publish --dry-run
      
      # - name: Publish Package
      #   run: |
      #       yes | flutter pub publish